import re

with open("src/lib/translations.ts", "r", encoding="utf-8") as f:
    content = f.read()

analyst_it = """
    app: {
      booting: "Avvio dell'ambiente sicuro...",
      unlock: "Sblocca",
      logout: "Esci",
      yourMind: "La tua Mente",
      panicMode: "Modalità Panico",
      analyzing: "Analisi...",
      change: "Cambia",
      noThoughts: "Non ci sono ancora pensieri registrati. Usa il microfono per iniziare.",
      limitedFeatures: "Funzionalità Limitate",
      privacyRejected: "Hai rifiutato l'Informativa sulla Privacy, pertanto le funzionalità di analisi IA sono state disabilitate.",
      acceptTermsToReactivate: "Per riattivarle, devi prima accettare i termini.",
      showTerms: "Mostra Termini",
      settings: "Impostazioni",
      theme: "Tema",
      light: "Chiaro",
      dark: "Scuro",
      language: "Lingua",
      autoLanguage: "Automatica",
      additionalFeatures: "Funzioni Aggiuntive",
      customizeExperience: "Personalizza la tua esperienza IA",
      apiKey: "Chiave API Gemini",
      configured: "Configurata",
      notConfigured: "Non configurata",
      securityAndAccount: "Sicurezza e Account",
      manageData: "Gestisci dati e protezione",
      exportThoughts: "Esporta Pensieri",
      downloadBackup: "Scarica un backup locale dei tuoi dati decifrati",
      dangerZone: "Zona Pericolosa",
      irreversibleActions: "Azioni irreversibili sull'account.",
      deleteAccountBtn: "Elimina Account e Tutti i Dati",
      gdprNotice: "Ai sensi del GDPR Art. 17 (diritto all'oblio), puoi richiedere la cancellazione completa e irreversibile di tutti i tuoi dati. L'operazione è permanente.",
      translating: "Traduzione in corso...",
      pleaseWait: "Attendere prego, non chiudere l'applicazione.",
      translateThoughtsTitle: "Traduzione Pensieri",
      translateThoughtsDesc: "Hai cambiato la lingua dell'interfaccia. Vuoi tradurre anche tutti i tuoi pensieri passati nella nuova lingua?",
      useAi: "Usa Intelligenza Artificiale",
      useAiDesc: "(Consigliato) Traduzione eccellente. I pensieri verranno inviati temporaneamente a Google Gemini. Richiede l'accettazione della Privacy.",
      useFreeTranslator: "Usa Traduttore Gratuito",
      useFreeTranslatorDesc: "ATTENZIONE: Si perde la crittografia Zero-Knowledge. I dati verranno inviati a un server di terze parti (MyMemory) per essere tradotti.",
      leaveOriginal: "Lascia in Lingua Originale",
      leaveOriginalDesc: "I pensieri passati rimarranno invariati.",
      timeCapsule: "Pergamena a tempo",
      linkCopied: "Link copiato negli appunti! L'app è pronta per essere condivisa.",
      translationCompleted: "Traduzione pensieri completata!",
      translationError: "Si è verificato un errore durante la traduzione dei pensieri.",
      deleteError: "Errore durante l'eliminazione: {{message}}. Se l'errore persiste, esegui di nuovo il login e riprova."
    },
    password: {
      vault: "Cassaforte",
      useBiometricsPrompt: "Usa il riconoscimento biometrico per sbloccare i tuoi pensieri.",
      usePasswordPrompt: "Inserisci la tua password per sbloccare i tuoi pensieri.",
      unlockWithFaceId: "Sblocca con Face ID",
      biometricFailed: "Autenticazione biometrica non riuscita. Inserisci la password.",
      usePasswordBtn: "Usa la password",
      useFaceIdBtn: "← Usa Face ID",
      passwordPlaceholder: "Password Cassaforte",
      enableBiometrics: "Abilita Face ID / Impronta",
      noMorePassword: "Non dovrai più digitare la password",
      unlockData: "Sblocca Dati",
      insertPasswordError: "Inserisci la tua password cassaforte.",
      unauthenticatedError: "Utente non autenticato. Ricarica la pagina.",
      credentialsNotFoundError: "Credenziali biometriche non trovate."
    },
    apiKey: {
      welcome: "Benvenuto in I Miei Pensieri",
      description: "Per garantire la tua privacy e nessuna limitazione, l'app richiede la tua API Key personale di Google AI Studio (completamente gratuita). Verrà crittografata con la tua password e salvata in modo sicuro.",
      howToGetIt: "Come ottenere la chiave:",
      goTo: "Vai su ",
      loginGoogle: "Accedi con il tuo account Google",
      createKey: "Crea una nuova API Key ed incollala qui sotto",
      privacyProtection: "Tutela della Privacy",
      privacyNotice: "Google si riserva il diritto di usare i dati delle API Key gratuite per addestrare i propri modelli. Per garantire che i tuoi pensieri restino privati al 100%, accedi alle impostazioni del tuo account Google AI Studio e disabilita la condivisione dei dati (Data Retention/Training Opt-out).",
      inputLabel: "La tua API Key Gemini",
      saveAndStart: "Salva e Inizia",
      continueWithout: "Continua senza API Key (Usa Default)"
    },
    nav: {
      thoughts: "Pensieri",
      analysis: "Analisi",
      options: "Opzioni",
      settings: "Impostazioni"
    },
    stats: {
      recordSomeThoughts: "Registra qualche pensiero per vedere le tue statistiche.",
      title: "Le Tue Statistiche",
      subtitle: "Andamento nel tempo dei tuoi pensieri e intensità",
      moodSummaryTitle: "Riepilogo dell'Umore",
      moodSummaryDesc: "Analisi degli ultimi 30 giorni",
      generateSummaryBtn: "Genera Riepilogo",
      missingApiKey: "API Key mancante.",
      noRecentThoughts: "Non ci sono pensieri recenti per generare un riepilogo.",
      summaryError: "Errore nella generazione del riepilogo",
      innerConnectionTitle: "Connessione Interiore",
      innerConnectionDesc: "Incrocio tra frequenza (quantità) e intensità (profondità) dei tuoi pensieri",
      veryHigh: "Altissima",
      good: "Buona",
      needsCultivation: "Da coltivare",
      frequencyTitle: "Frequenza dei pensieri",
      frequencyDesc: "Quanti pensieri hai registrato ogni giorno",
      thoughtsLabel: "Pensieri",
      intensityTitle: "Intensità Emotiva (1-10)",
      intensityDesc: "La profondità analizzata dall'IA giorno per giorno",
      depthLabel: "Profondità"
    },
    profile: {
      missingApiKeyTitle: "Chiave API Mancante",
      missingApiKeyDesc: "Per utilizzare l'Analisi Psicologica devi inserire la chiave API Gemini nelle Impostazioni.",
      recordMoreThoughts: "Registra qualche pensiero in più per sbloccare l'analisi psicologica.",
      title: "Analisi Personale",
      subtitle: "Un overview onesta basata sui tuoi pensieri.",
      refresh: "Aggiorna",
      warning: "Attenzione:",
      recordedOnly: "Hai registrato solo",
      thoughtSingular: "pensiero",
      thoughtPlural: "pensieri",
      unreliableAnalysis: "L'analisi mostrata qui sotto è molto sommaria e potenzialmente non affidabile. Continua ad aggiungere pensieri (ne consigliamo almeno 5) per delineare un profilo più accurato.",
      analyzingText: "Analisi in corso, la verità nuda e cruda...",
      toDeepen: "Per approfondire",
      byAuthor: "di",
      toChallenge: "Per sfidare le certezze",
      downloadApps: "Scarica le app ufficiali (iOS & Android)"
    },
    thoughtCard: {
      editWithVoice: "Modifica con la voce",
      deleteThought: "Elimina pensiero",
      confirmDelete: "Vuoi davvero eliminare questo pensiero?",
      cancel: "Annulla",
      deleteBtn: "Elimina",
      youAreSaying: "Stai dicendo:",
      sealedInCapsule: "Pensiero sigillato nella Capsula del Tempo.",
      willOpenOn: "Si aprirà il",
      location: "Posizione",
      openInMaps: "Apri in Google Maps",
      updateError: "Errore durante l'aggiornamento del pensiero.",
      editError: "Errore durante la modifica."
    },
    connection: {
      disconnected: "Disconnesso",
      reconnecting: "In Riconnessione",
      goodAlignment: "Buon Allineamento",
      deepConnection: "Profonda Connessione",
      analysisTitle: "Analisi della Connessione",
      last7Days: "Ultimi 7 giorni",
      infoLabel: "Informazioni sulla connessione",
      recordedThoughts: "{{count}} {{noun}} registrat{{suffix}}",
      howItWorks: "Come funziona?",
      description1: "Questo indicatore riflette l'intensità della tua connessione interiore. Non si basa solo su quanti pensieri registri, ma premia la profondità introspettiva di ciò che esprimi.",
      description2: "Più rifletti autenticamente e frequentemente, più la barra si completa indicando un forte allineamento con te stesso."
    },
"""

analyst_en = """
    app: {
      booting: "Starting secure environment...",
      unlock: "Unlock",
      logout: "Log out",
      yourMind: "Your Mind",
      panicMode: "Panic Mode",
      analyzing: "Analyzing...",
      change: "Change",
      noThoughts: "No thoughts recorded yet. Use the microphone to start.",
      limitedFeatures: "Limited Features",
      privacyRejected: "You rejected the Privacy Policy, so AI analysis features have been disabled.",
      acceptTermsToReactivate: "To reactivate them, you must first accept the terms.",
      showTerms: "Show Terms",
      settings: "Settings",
      theme: "Theme",
      light: "Light",
      dark: "Dark",
      language: "Language",
      autoLanguage: "Auto",
      additionalFeatures: "Additional Features",
      customizeExperience: "Customize your AI experience",
      apiKey: "Gemini API Key",
      configured: "Configured",
      notConfigured: "Not configured",
      securityAndAccount: "Security & Account",
      manageData: "Manage data and protection",
      exportThoughts: "Export Thoughts",
      downloadBackup: "Download a local backup of your decrypted data",
      dangerZone: "Danger Zone",
      irreversibleActions: "Irreversible account actions.",
      deleteAccountBtn: "Delete Account and All Data",
      gdprNotice: "Under GDPR Art. 17 (Right to Erasure), you can request the complete and irreversible deletion of all your data. This operation is permanent.",
      translating: "Translating...",
      pleaseWait: "Please wait, do not close the application.",
      translateThoughtsTitle: "Translate Thoughts",
      translateThoughtsDesc: "You changed the interface language. Do you also want to translate all your past thoughts into the new language?",
      useAi: "Use Artificial Intelligence",
      useAiDesc: "(Recommended) Excellent translation. Thoughts will be temporarily sent to Google Gemini. Requires accepting the Privacy Policy.",
      useFreeTranslator: "Use Free Translator",
      useFreeTranslatorDesc: "WARNING: Zero-Knowledge encryption is lost. Data will be sent to a third-party server (MyMemory) to be translated.",
      leaveOriginal: "Keep Original Language",
      leaveOriginalDesc: "Past thoughts will remain unchanged.",
      timeCapsule: "Time Capsule",
      linkCopied: "Link copied to clipboard! The app is ready to be shared.",
      translationCompleted: "Thoughts translation completed!",
      translationError: "An error occurred while translating thoughts.",
      deleteError: "Error during deletion: {{message}}. If the error persists, please log in again and retry."
    },
    password: {
      vault: "Vault",
      useBiometricsPrompt: "Use biometric recognition to unlock your thoughts.",
      usePasswordPrompt: "Enter your password to unlock your thoughts.",
      unlockWithFaceId: "Unlock with Face ID",
      biometricFailed: "Biometric authentication failed. Enter your password.",
      usePasswordBtn: "Use password",
      useFaceIdBtn: "← Use Face ID",
      passwordPlaceholder: "Vault Password",
      enableBiometrics: "Enable Face ID / Fingerprint",
      noMorePassword: "You won't have to type your password anymore",
      unlockData: "Unlock Data",
      insertPasswordError: "Please enter your vault password.",
      unauthenticatedError: "User not authenticated. Please reload the page.",
      credentialsNotFoundError: "Biometric credentials not found."
    },
    apiKey: {
      welcome: "Welcome to My Thoughts",
      description: "To ensure your privacy and no limitations, the app requires your personal Google AI Studio API Key (completely free). It will be encrypted with your password and saved securely.",
      howToGetIt: "How to get the key:",
      goTo: "Go to ",
      loginGoogle: "Log in with your Google account",
      createKey: "Create a new API Key and paste it below",
      privacyProtection: "Privacy Protection",
      privacyNotice: "Google reserves the right to use data from free API Keys to train its models. To ensure your thoughts remain 100% private, access your Google AI Studio account settings and disable data sharing (Data Retention/Training Opt-out).",
      inputLabel: "Your Gemini API Key",
      saveAndStart: "Save and Start",
      continueWithout: "Continue without API Key (Use Default)"
    },
    nav: {
      thoughts: "Thoughts",
      analysis: "Analysis",
      options: "Options",
      settings: "Settings"
    },
    stats: {
      recordSomeThoughts: "Record some thoughts to see your statistics.",
      title: "Your Statistics",
      subtitle: "Trend of your thoughts and intensity over time",
      moodSummaryTitle: "Mood Summary",
      moodSummaryDesc: "Analysis of the last 30 days",
      generateSummaryBtn: "Generate Summary",
      missingApiKey: "Missing API Key.",
      noRecentThoughts: "No recent thoughts to generate a summary.",
      summaryError: "Error generating the summary",
      innerConnectionTitle: "Inner Connection",
      innerConnectionDesc: "Intersection between frequency (quantity) and intensity (depth) of your thoughts",
      veryHigh: "Very High",
      good: "Good",
      needsCultivation: "Needs Cultivation",
      frequencyTitle: "Thought Frequency",
      frequencyDesc: "How many thoughts you recorded each day",
      thoughtsLabel: "Thoughts",
      intensityTitle: "Emotional Intensity (1-10)",
      intensityDesc: "The depth analyzed by AI day by day",
      depthLabel: "Depth"
    },
    profile: {
      missingApiKeyTitle: "Missing API Key",
      missingApiKeyDesc: "To use Psychological Analysis you must enter your Gemini API Key in Settings.",
      recordMoreThoughts: "Record a few more thoughts to unlock psychological analysis.",
      title: "Personal Analysis",
      subtitle: "An honest overview based on your thoughts.",
      refresh: "Refresh",
      warning: "Warning:",
      recordedOnly: "You have recorded only",
      thoughtSingular: "thought",
      thoughtPlural: "thoughts",
      unreliableAnalysis: "The analysis shown below is very brief and potentially unreliable. Keep adding thoughts (we recommend at least 5) to outline a more accurate profile.",
      analyzingText: "Analysis in progress, the naked truth...",
      toDeepen: "To deepen",
      byAuthor: "by",
      toChallenge: "To challenge your certainties",
      downloadApps: "Download the official apps (iOS & Android)"
    },
    thoughtCard: {
      editWithVoice: "Edit with voice",
      deleteThought: "Delete thought",
      confirmDelete: "Do you really want to delete this thought?",
      cancel: "Cancel",
      deleteBtn: "Delete",
      youAreSaying: "You are saying:",
      sealedInCapsule: "Thought sealed in the Time Capsule.",
      willOpenOn: "It will open on",
      location: "Location",
      openInMaps: "Open in Google Maps",
      updateError: "Error updating the thought.",
      editError: "Error during editing."
    },
    connection: {
      disconnected: "Disconnected",
      reconnecting: "Reconnecting",
      goodAlignment: "Good Alignment",
      deepConnection: "Deep Connection",
      analysisTitle: "Connection Analysis",
      last7Days: "Last 7 days",
      infoLabel: "Connection information",
      recordedThoughts: "{{count}} {{noun}} recorded",
      howItWorks: "How does it work?",
      description1: "This indicator reflects the intensity of your inner connection. It is not only based on how many thoughts you record, but rewards the introspective depth of what you express.",
      description2: "The more authentically and frequently you reflect, the more the bar fills up indicating a strong alignment with yourself."
    },
"""

def insert_into_dict(content, dict_name, dict_content):
    pattern = rf"(export const translations = {{\s+{dict_name}:\s+{{)"
    return re.sub(pattern, r"\1\n" + dict_content, content, count=1)

content = insert_into_dict(content, "it", analyst_it)
content = insert_into_dict(content, "en", analyst_en)

with open("src/lib/translations.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("Translations updated successfully.")
